-- ============================================
-- MIGRATION 30: Populate 3 Missing Journeys
-- ============================================
-- Created: 2026-03-06
-- Agent: @data-engineer (Dara)
-- Purpose: Re-populate 3 incomplete clinical journeys with 12 sessions each
--
-- Journeys to populate:
--   1. 550e8400-e29b-41d4-a716-446655440002 (Depressão — João)
--   2. 550e8400-e29b-41d4-a716-446655440001 (Agorafobia — Maria)
--   3. 550e8400-e29b-41d4-a716-446655440000 (TAG — Pedro)
--
-- Template: journey-013 (Transtorno de Pânico — 12 sessions)
--
-- Total inserts: 36 (3 journeys × 12 sessions)
-- Idempotent: YES (IF NOT EXISTS logic)
-- Reversible: YES (see rollback script)
--
-- HOW TO USE:
--   1. Open Supabase SQL Editor (project vhwpohwklbguizaixitv)
--   2. Paste this ENTIRE script
--   3. Click "Run"
--   4. Check output for success/conflicts
--
-- ============================================

BEGIN;

-- ============================================
-- STEP 1: Snapshot existing data (backup)
-- ============================================
CREATE TEMPORARY TABLE backup_journey_sessions_pre AS
SELECT * FROM journey_sessions
WHERE journey_id IN (
  '550e8400-e29b-41d4-a716-446655440002',
  '550e8400-e29b-41d4-a716-446655440001',
  '550e8400-e29b-41d4-a716-446655440000'
);

-- ============================================
-- STEP 2: Insert 12 sessions for Depressão (João)
-- Journey ID: 550e8400-e29b-41d4-a716-446655440002
-- ============================================

INSERT INTO journey_sessions (
  id, journey_id, session_number, session_title, session_phase,
  context, options, created_at, updated_at
) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 1,
 'Estabelecendo Aliança e Psicoeducação Inicial sobre Depressão',
 'initial',
 'João, 38 anos, analista de sistemas, chega relatando desmotivação persistente, falta de prazer em atividades, e sensação de estar "parado" há 3 meses apesar de sucesso profissional aparente. Apresenta crenças centrais: "Eu falho em ser bom o suficiente", "Meu valor está no que produzo". O foco inicial é estabelecer aliança terapêutica e psicoeducação sobre depressão (DSM-5-TR: Episódio Moderado de Transtorno Depressivo Recorrente). Objetivos: recuperar interesse, reduzir autocrítica, desenvolver estratégias para períodos de baixa energia.',
 '[{"option_letter":"A","intervention":"Psicoeducação baseada em evidências sobre depressão maior e modelo cognitivo-comportamental","approach":"Validação + esperança realista","is_optimal":true,"impact":{"rapport":8,"insight":7,"behavioral_change":6,"symptom_reduction":0}},{"option_letter":"B","intervention":"Focar imediatamente em tarefas comportamentais para "sair da cama"","approach":"Ativação comportamental direta sem contexto","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":5,"symptom_reduction":0}},{"option_letter":"C","intervention":"Explorar traumas passados antes de abordar sintomas atuais","approach":"Psicanálise exploratória","is_optimal":false,"impact":{"rapport":5,"insight":6,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Prescrever medicação e minimizar o componente psicológico","approach":"Medicalização sem contexto","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":3,"symptom_reduction":0}}]'::jsonb,
 NOW(), NOW()
)
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 2, 'Mapeando o Ciclo Depressivo: Comportamento, Pensamento e Emoção', 'middle', 'João traz registros de atividades do último semestre. Você identifica uma queda gradual em atividades que antes o traziam prazer (esportes, tempo com amigos). Ele relata pensamentos catastróficos frequentes: "Nunca vou melhorar", "Sou um fracasso". A sessão foca em psicoeducação sobre o ciclo da depressão: redução de atividade → mais pensamentos negativos → apatia aumentada. Você e João mapeiam esse ciclo em sua vida específica, conectando cada comportamento de evitação a um pensamento depressogênico. A meta: identificar um ponto de intervenção viável.', '[{"option_letter":"A","intervention":"Colaborativamente identificar UMA atividade pequena para retomar esta semana (ativação comportamental graduada)","approach":"Abordagem colaborativa de pequenos passos","is_optimal":true,"impact":{"rapport":8,"insight":7,"behavioral_change":8,"symptom_reduction":0}},{"option_letter":"B","intervention":"Prescrever 5 atividades novas para quebrar o ciclo rapidamente","approach":"Prescrição agressiva","is_optimal":false,"impact":{"rapport":4,"insight":5,"behavioral_change":3,"symptom_reduction":0}},{"option_letter":"C","intervention":"Focar apenas em mudanças de pensamento via reestruturação cognitiva","approach":"Cognição sem comportamento","is_optimal":false,"impact":{"rapport":6,"insight":6,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Aconselhar João a "apenas descansar mais"","approach":"Reforço da evitação","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 3, 'Ativação Comportamental: Pequenos Passos, Grande Impacto', 'middle', 'João relata que retomou futebol com amigos uma vez na semana anterior. Humor ligeiramente melhorado, mas também crítica: "Deveria estar fazendo mais." Você valida o progresso e reenquadra a autocrítica como parte do transtorno, não como verdade. Sessão aprofunda a ativação comportamental: planejamento de 3-4 atividades pequenas para a semana com foco em valor pessoal (não em obrigação). Discussão sobre como a depressão distorce a percepção de "suficiência". Introduz registro de humor x atividade para validar correlação.', '[{"option_letter":"A","intervention":"Validar progresso, discutir autocrítica como sintoma depressivo, e planejar 3 atividades pequenas mas significativas","approach":"Validação + psicoeducação + planejamento","is_optimal":true,"impact":{"rapport":9,"insight":8,"behavioral_change":9,"symptom_reduction":0}},{"option_letter":"B","intervention":"Aumentar drasticamente as demandas ("agora você precisa fazer exercício, trabalho voluntário, e cursos")","approach":"Sobrecarga","is_optimal":false,"impact":{"rapport":3,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Parar a ativação e voltar a explorar causas profundas da depressão em história passada","approach":"Exploração histórica","is_optimal":false,"impact":{"rapport":6,"insight":5,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir que "trabalho é seu problema" e pedir licença","approach":"Evitação de responsabilidade","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 4, 'Identificando e Desafiando Crenças Centrais Depressivas', 'middle', 'João traz um padrão de pensamentos: quando comete um pequeno erro no trabalho, sente que é "um fracasso total". Você mapeia a crença central: "Meu valor = meu desempenho". Sessão introduz técnicas de reestruturação cognitiva: busca de evidências contra a crença, experimentos comportamentais. Você o desafia: "Quando você comete um erro, você automaticamente vira um fracasso? Ou é uma pessoa complexa que às vezes erra?" Discussão sobre valor intrínseco vs. condicionado.', '[{"option_letter":"A","intervention":"Colaborativamente explorar a origem dessa crença e testar com pequenos experimentos comportamentais","approach":"Reestruturação cognitiva + experimentos","is_optimal":true,"impact":{"rapport":8,"insight":9,"behavioral_change":7,"symptom_reduction":1}},{"option_letter":"B","intervention":"Diretamente contradizer: "Isso é ilógico, você é mais do que seu trabalho"","approach":"Confrontação direta","is_optimal":false,"impact":{"rapport":4,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aceitar a crença como verdadeira e trabalhar em "aceitar" ser um fracasso","approach":"Aceitação prematura","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Ignorar o padrão e focar em relaxamento/meditação","approach":"Evitação da cognição","is_optimal":false,"impact":{"rapport":5,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 5, 'Expandindo Valores e Reengajamento Social', 'middle', 'João compartilha que passou mais tempo com amigos e até iniciou um projeto pessoal (programação, hobby antigo). Humor notavelmente melhor. Você consolida a ideia de que reconectar com valores pessoais, não apenas obrigações, move a agulha. Sessão identifica outras áreas de vida: relacionamentos, criatividade, contribuição comunitária. Trabalha em planejar reengajamento gradual em cada área. Discussão sobre como a depressão rouba essas conexões e como recuperá-las é ato de resistência.', '[{"option_letter":"A","intervention":"Celebrar progresso, mapear valores em 4 áreas de vida (trabalho, relacionamentos, saúde, criatividade), e planejar reengajamento gradual","approach":"Consolidação + mapeamento de valores","is_optimal":true,"impact":{"rapport":9,"insight":8,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Aumentar expectativas abruptamente ("você está bem agora, volta ao trabalho 100%")","approach":"Sobrecarga","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":3,"symptom_reduction":0}},{"option_letter":"C","intervention":"Manter foco exclusivo em trabalho ("esse é seu maior problema")","approach":"Redução de perspectiva","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir que terapia já fez seu trabalho e encerrar","approach":"Encerramento prematuro","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 6, 'Consolidação e Plano de Prevenção de Recaída', 'advanced', 'João relata 4 semanas consecutivas de melhora. Energia está retornando, mas expressa medo: "E se voltar?" Sessão foca em prevenção de recaída: identificar gatilhos (períodos de alto estresse, isolamento), sinais de alerta precoce (redução de atividades, isolamento), e plano de ação (reativar estratégias, buscar apoio, considerar booster de terapia). Você e João criam um "mapa de bem-estar" com estratégias-chave da terapia. Discussão sobre como depressão é episódica, mas ferramentas aprendidas são permanentes.', '[{"option_letter":"A","intervention":"Colaborativamente criar plano de prevenção de recaída identificando gatilhos, sinais de alerta, e estratégias de resposta rápida","approach":"Planejamento colaborativo preventivo","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Garantir que "nunca vai recair se seguir tudo perfeitamente"","approach":"Falsas garantias","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Simplificar: "Apenas continue fazendo o que está fazendo"","approach":"Superficialidade","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Prescrever medicação adicional como "proteção"","approach":"Medicalização preventiva","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 7, 'Navegando Recaída Leve: Fortalecendo Resiliência', 'advanced', 'Uma semana de sintomas leves reaparece (apatia, pensamentos críticos) após período estressante no trabalho. João fica ansioso, mas consegue reconhecer o padrão. Você normaliza como esperado, não fracasso. Sessão reativa ferramentas: volta a atividades valorizadas imediatamente, desafia pensamentos catastróficos, reforça autocompaixão. Introduz conceito de "recaída vs. recorrência": pequenos episódios de sintomas são normais e tratáveis rapidamente com conhecimento das ferramentas.', '[{"option_letter":"A","intervention":"Normalizar como esperado, reativar ferramentas imediatamente, e reforçar que João tem agora know-how para lidar","approach":"Normalização + ativação imediata","is_optimal":true,"impact":{"rapport":9,"insight":8,"behavioral_change":8,"symptom_reduction":3}},{"option_letter":"B","intervention":"Sugerir que falhou e precisa de medicação forte/internação","approach":"Catastrofização","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}},{"option_letter":"C","intervention":"Parar todas as estratégias e "apenas descansar"","approach":"Repouso sem contexto","is_optimal":false,"impact":{"rapport":5,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Explorar "por que recaiu" em vez de agir","approach":"Análise paralisante","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 8, 'Aprofundando Autocompaixão: Aceitação vs. Luta contra Pensamentos', 'advanced', 'Sintomas leves já melhoraram com ativação rápida. Foco muda para autocompaixão: João percebe que sua autocrítica ("Deveria estar 100% melhor") mantém tensão. Sessão introduz conceitos de ACT (Acceptance and Commitment Therapy) complementar: observar pensamentos sem compra, valores reais (não perfeição). Exercício de mindfulness para noticing vs. fusing com pensamentos críticos internos.', '[{"option_letter":"A","intervention":"Introduzir aceitação psicológica e distancing de pensamentos via mindfulness; reforçar que luta contra sintomas os mantém","approach":"ACT + Mindfulness","is_optimal":true,"impact":{"rapport":8,"insight":9,"behavioral_change":7,"symptom_reduction":2}},{"option_letter":"B","intervention":"Aumentar confrontação cognitiva ("elimine esses pensamentos ruins")","approach":"Luta contra pensamentos","is_optimal":false,"impact":{"rapport":4,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Focar exclusivamente em relaxamento corporal","approach":"Física sem psicologia","is_optimal":false,"impact":{"rapport":6,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir que aceitação = resignação e render-se à depressão","approach":"Mal-entendido de aceitação","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 9, 'Integração de Valores com Ação: Vida Significativa além da Depressão', 'advanced', 'João agora está consistentemente melhor. Energizado. Discussão passa para: "Como quero viver minha vida?" Conecta valores identificados (relacionamento, criatividade, contribuição) com ações concretas. Planeja conversa significativa com esposa, retomada de projeto de programação como possível negócio futuro, voluntariado em ONG de tecnologia. Sessão consolida que saúde mental não é apenas ausência de sintomas, mas presença de uma vida significativa.', '[{"option_letter":"A","intervention":"Mapear valores profundos e co-criar plano de vida significativa alinhado com esses valores, além de sintomas","approach":"Life Values Integration","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Retomar foco exclusivo em "eliminar sintomas completamente"","approach":"Regressão a sintomatologia","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":3,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir que já está bem e não precisa fazer mais nada","approach":"Estagnação","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Focar em "ser realista" e aceitar uma vida medíocre","approach":"Diminuição de esperança","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 10, 'Sustentabilidade a Longo Prazo: Conhecimento Adquirido', 'advanced', 'João compartilha planos concretos: encontro em família planejado, projeto iniciado, primeira reunião de voluntariado agendada. Humor estável, autocrítica reduzida significativamente. Sessão revisa o trajectory: depressão moderada → recuperação → vida significativa. Consolida que o know-how para lidar com futuras dificuldades é permanente. Discussão sobre monitoramento contínuo de sinais de alerta e quando buscar reforço terapêutico.', '[{"option_letter":"A","intervention":"Revisar trajectory completo, consolidar ferramentas, discutir monitoramento contínuo e momento de retorno se necessário","approach":"Consolidação + autonomy","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":3}},{"option_letter":"B","intervention":"Prescrever sessões frequentes "como manutenção"","approach":"Dependência terapêutica","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Encerrar abruptamente e não discutir follow-up","approach":"Abandono","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Focar em "tudo pode recair" e elevar ansiedade","approach":"Alarmismo","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 11, 'Reflexão sobre Jornada: Do Vazio ao Propósito', 'termination', 'Sessão reflexiva. João fala sobre transformação: começou sentindo-se vazio, sem propósito, preso em autocrítica. Agora tem direção, relacionamentos reforçados, atividades significativas. Reconhece que depressão ainda pode surgir em momentos de estresse, mas tem ferramentas e compreensão para lidar. Discussão sobre o que aprendeu sobre si mesmo: que valor intrínseco não depende de produtividade, que conexão humana importa, que pequenos passos criam momentum.', '[{"option_letter":"A","intervention":"Facilitar reflexão profunda sobre jornada, integrar aprendizados, celebrar resiliência, discutir legado das ferramentas","approach":"Integrative Closure","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":3}},{"option_letter":"B","intervention":"Focar em possíveis limitações que ainda restam","approach":"Foco no negativo","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Pressionar para "uma última sessão para garantir"","approach":"Prolongamento artificial","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar rapidamente sem processamento","approach":"Encerramento apressado","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440002', 12, 'Encerramento e Manutenção Autônoma de Bem-Estar', 'termination', 'Sessão final. João chegará independente, levando consigo mapa de bem-estar, identificação de gatilhos, ferramentas TCC (ativação comportamental, reestruturação cognitiva, autocompaixão), e plano de recaída. Você revisa: "Você é agora especialista em sua própria saúde mental." Encerram com discussão sobre continuidade de vida significativa, redes de apoio (amigos, família, grupo de voluntariado), e porta aberta para booster sessions se necessário. João sai com sentido de competência restaurado.', '[{"option_letter":"A","intervention":"Consolidar autonomia, revisar ferramentas portáteis, celebrar e deixar porta aberta para retorno futuro","approach":"Autonomous Maintenance","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":3}},{"option_letter":"B","intervention":"Prescrever medicação para "manutenção" indefinida","approach":"Dependência medicamentosa","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir terapia indefinida","approach":"Dependência terapêutica indefinida","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar com aviso de "nunca vai estar realmente curado"","approach":"Desempoderamento","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- ============================================
-- STEP 3: Insert 12 sessions for Agorafobia (Maria)
-- Journey ID: 550e8400-e29b-41d4-a716-446655440001
-- ============================================
-- Template: Journey-013 adapted (Panic as core, Agoraphobia as primary difficulty)

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 1, 'Entendendo Agorafobia: Além do Medo de Sair de Casa', 'initial', 'Maria, 45 anos, relata 2 anos progressivos de evitação: começou com medo de dirigir em rodovias, agora evita sair de casa sozinha. Descreve ataques de pânico em espaços abertos ou "sem saída fácil". Crença central: "Se tenho um ataque, ninguém vai conseguir me ajudar." O foco inicial é psicoeducação sobre agorafobia: não é medo de sair, mas medo da própria ansiedade em contextos onde escape é difícil. Estabelece aliança terapêutica e esperança de que exposição graduada é eficaz.', '[{"option_letter":"A","intervention":"Psicoeducação colaborativa sobre agorafobia como transtorno de ansiedade, não fraqueza, com esperança de recuperação via exposição","approach":"Validação + Esperança baseada em evidência","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":5,"symptom_reduction":0}},{"option_letter":"B","intervention":"Focar em medicação ansiolítica como "solução"","approach":"Medicalização sem contexto","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":2,"symptom_reduction":1}},{"option_letter":"C","intervention":"Constranger Maria a sair de casa imediatamente","approach":"Exposição não colaborativa","is_optimal":false,"impact":{"rapport":2,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Aceitar evitação como "maneira de viver" e adaptar vida","approach":"Acomodação da fobia","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 2, 'Mapeando Hierarquia de Medo: Da Sala para o Mundo', 'middle', 'Maria consegue se mover pela casa com ansiedade mínima. Medo sobe ao sair para quintal (moderado), sair da rua (alto), ir ao supermercado (muito alto), dirigir (extremo). Você monta hierarquia de exposição (SUDS 10-100). Começam com meta pequena: passar 5 minutos no quintal sem comportamento de segurança (evitar, chamar marido, etc.). Discussão sobre como comportamentos de segurança perpetuam agorafobia.', '[{"option_letter":"A","intervention":"Colaborativamente criar hierarquia graduada de exposição começando com muito pequeno (quintal), sem pressão","approach":"Exposure Hierarchy Planning","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":7,"symptom_reduction":0}},{"option_letter":"B","intervention":"Começar com exposição de nível alto (supermercado) para "pular etapas"","approach":"Exposição acelerada","is_optimal":false,"impact":{"rapport":3,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Focar em relaxação/meditação antes de qualquer exposição","approach":"Atraso de exposição","is_optimal":false,"impact":{"rapport":6,"insight":5,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir que problema é casamento ("seu marido te protege demais")","approach":"Exploração não produtiva","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 3, 'Primeira Exposição: Quebra da Evitação', 'middle', 'Maria conseguiu ficar no quintal 5 minutos 3 vezes na semana. Ansiedade subiu para 7/10 inicialmente, caiu para 3/10 ao final. Percebe habituação natural. Marido participou (inicialmente ajudando, depois mantendo distância). Sessão valida a coragem, explica mecanismo de habituação, aumenta levemente a meta: 10 minutos no quintal, depois caminhar até o portão (sem sair da propriedade). Importante: sem marido ao lado.', '[{"option_letter":"A","intervention":"Celebrar, explicar habituação, aumentar meta graduadamente, e enfatizar importância de fazer sozinha","approach":"Gradual + Autonomy","is_optimal":true,"impact":{"rapport":9,"insight":8,"behavioral_change":8,"symptom_reduction":1}},{"option_letter":"B","intervention":"Pressionar para "já ir longe" (supermercado)","approach":"Aceleração agressiva","is_optimal":false,"impact":{"rapport":3,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Permitir marido ao lado em todas exposições","approach":"Acomodação contínua","is_optimal":false,"impact":{"rapport":6,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir que "ansiedade é demais" e aumentar medicação","approach":"Evitação via medicação","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 4, 'Expandindo para Espaços Públicos: Rua e Vizinhança', 'middle', 'Maria conseguiu caminhar até o portão várias vezes, sozinha. Ansiedade habituou (4-5/10). Próximo passo: caminhar 100 metros na rua, sozinha, sem marido seguindo disfarçado. Medo central: "Se tenho um ataque aqui e ninguém conhece, vou desmaiar e ninguém vai me ajudar." Você reestructura: "Em 45 anos, você desmaiou alguma vez durante um ataque?" Resposta: "Não." "Então qual é a evidência de que vai desmaiar agora?" Trabalha em desafiar a crença catastrófica enquanto planejam exposição.', '[{"option_letter":"A","intervention":"Reestruturar crença catastrófica via evidência, planejar rua com marido a distância (não visível), suporte telefone se pânico máximo","approach":"Cognitive Restructuring + Graduated Exposure","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":7,"symptom_reduction":1}},{"option_letter":"B","intervention":"Permitir marido ao lado constantemente","approach":"Dependency Perpetuation","is_optimal":false,"impact":{"rapport":6,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir que " saúde é mais importante que exposição" e encerrar esse passo","approach":"Avoidance Enabled","is_optimal":false,"impact":{"rapport":5,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Aumentar medicação ansiolítica para permitir sair","approach":"Medicação como substitute","is_optimal":false,"impact":{"rapport":4,"insight":1,"behavioral_change":2,"symptom_reduction":1}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 5, 'Conquista Modulada: Do Bairro ao Shopping', 'middle', 'Maria agora consegue caminhar 500 metros sozinha, com ansiedade habituando (3-4/10). Confiança aumentando. Medo persistente: espaços fechados (shopping, cinema). Teme estar preso sem saída rápida. Você trabalha em plano: visita ao shopping durante horário vazio, focando em entrar, permanecer 5 minutos perto da entrada, sair. Sem compras, sem stress adicional. Marido pode estar no estacionamento, não dentro.', '[{"option_letter":"A","intervention":"Planejar exposição gradual em shopping começando perto de saída, sem marido dentro, com saída rápida planejada","approach":"Anxiety-Hierarchy Respecting","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":8,"symptom_reduction":1}},{"option_letter":"B","intervention":"Levar marido para dentro do shopping para "segurança"","approach":"Security Behavior Reinforcement","is_optimal":false,"impact":{"rapport":6,"insight":4,"behavioral_change":3,"symptom_reduction":0}},{"option_letter":"C","intervention":"Pular shopping e focar em dirigir (hierarquia mais alta)","approach":"Premature Escalation","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir compras online em vez de exposição","approach":"Avoidance Accommodation","is_optimal":false,"impact":{"rapport":5,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 6, 'Consolidação e Desafio do Passo Mais Alto: Direção', 'advanced', 'Maria passou 20 minutos em shopping, ansiedade habituou significativamente (2-3/10). Vida começou a retornar: saiu com amigas para café, algo impensável 6 meses atrás. Agora enfrenta medão: dirigir sozinha em rodovia (era o problema original). Sessão planeja exposição faseada: dirija em rua de bairro, depois via principal, depois mini-rodovia, depois rodovia. Exposição interoceptiva complementar: se taquicardia surge dirigindo (esperado), o que você fará? Resposta planejada: "Respiro, continuo dirigindo, a taquicardia passa."', '[{"option_letter":"A","intervention":"Planejar dirección faseada com exposição interoceptiva, reforçar que taquicardia durante direção é normalmente esperada e não perigosa","approach":"Hierarchical + Interoceptive","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Adiar dirigir e "trabalhar mais em ansiedade geral"","approach":"Avoidance of Hierarchy Top","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir medicação ansiolítica antes de dirigir","approach":"Pharmaceutical Crutch","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":2,"symptom_reduction":1}},{"option_letter":"D","intervention":"Permitir marido dirigir com Maria como passageira por agora","approach":"Postponed Exposure","is_optimal":false,"impact":{"rapport":6,"insight":3,"behavioral_change":2,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 7, 'Manejo de Ansiedade Residual e Aprofundamento de Aceitação', 'advanced', 'Maria conseguiu dirigir em via principal 2 vezes, com ansiedade alta inicialmente, mas habituando. Rodovia ainda é terrorizante. Ela relata: "Ainda tenho pânico, mas agora continuo fazendo o que preciso fazer." Sessão aprofunda aceitação psicológica: não é sobre eliminar 100% da ansiedade, mas sobre agir alinhada com valores mesmo com ansiedade presente. Introduz ACT: presença com ansiedade, não luta contra ela.', '[{"option_letter":"A","intervention":"Reforçar que valor de ação é mais importante que ausência de sintomas; ensinar presença com ansiedade sem fuga","approach":"ACT + Values Alignment","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Focar em eliminar 100% da ansiedade via meditação","approach":"Symptom Elimination Focus","is_optimal":false,"impact":{"rapport":6,"insight":5,"behavioral_change":3,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aumentar medicação para "controlar" a ansiedade","approach":"Pharmaceutical Escalation","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":2,"symptom_reduction":1}},{"option_letter":"D","intervention":"Sugerir que "talvez não é para você" e parar","approach":"Defeatism","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 8, 'Rodovia: Conquista do Medão Final', 'advanced', 'Maria dirigiu em rodovia por 15 km com marido no banco de passageiro (não dirigindo, não assumindo controle). Ansiedade subiu, habituou, conseguiu voltar para casa sozinha. Descreveu sentimento de "libertação" e "confiança restaurada". Sessão celebra a conquista, consolida que conseguiu enfrentar o pior medo. Planeja viagem de fim de semana para validar a nova capacidade. Discussão sobre como agorafobia a mantinha prisioneira, mas exposição lhe devolveu liberdade.', '[{"option_letter":"A","intervention":"Celebrar magnitude da conquista, consolidar ganhos, planejar atividades futuras que antes evitava, validar libertação","approach":"Celebration + Consolidation","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Focar em "ainda há ansiedade" e indicar mais tratamento","approach":"Problem Focus Instead of Gains","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir que "rodovia é bastante, agora vamos parar aqui"","approach":"Premature Plateau","is_optimal":false,"impact":{"rapport":6,"insight":4,"behavioral_change":2,"symptom_reduction":1}},{"option_letter":"D","intervention":"Pressionar para viagens ainda mais longas imediatamente","approach":"Pressure to Escalate","is_optimal":false,"impact":{"rapport":3,"insight":2,"behavioral_change":2,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 9, 'Retomada de Vida Social e Independência', 'advanced', 'Maria fez fim de semana em praia com marido, dirigindo 2 horas sozinha. Saiu com amigas para café, cinema, shopping sem pânico significativo. Vida social ressurgiu. Confiança em estar em espaços públicos restaurada. Sessão consolida essa transformação: era agorafóbica severamente restrita, agora tem liberdade. Discussão sobre manutenção: continuar tendo exposições (dirigir, sair sozinha) regularmente para manter ganhos.', '[{"option_letter":"A","intervention":"Celebrar retomada de vida normal, enfatizar continuidade de exposição como manutenção, deixar porta aberta para reforços","approach":"Maintenance Planning + Autonomy","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Aumentar frequência de terapia para "manutenção"","approach":"Dependency on Therapy","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir terapia indefinida para "prevenção"","approach":"Perpetual Treatment","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar abruptamente sem discussão de manutenção","approach":"Abrupt Termination","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 10, 'Plano de Recaída: Vigilância e Ação Rápida', 'termination', 'Maria e terapeuta criam plano de recaída. Gatilhos identificados: períodos de alto stress, isolamento, não dirigir por semanas. Sinais de alerta precoce: evitar sair "por motivos pequenos", pensar em marido dirigindo em vez de ela. Plano de ação: reativar exposição imediatamente (sair, dirigir curta distância), contatar terapeuta se ansiedade interfere com vida. Enfatizado: pequenas recaídas são normais, mas ação rápida previne retorno à agorafobia severa.', '[{"option_letter":"A","intervention":"Colaborativamente criar plano de recaída detalhado com gatilhos, sinais de alerta, e ações imediatas; normalizar episódios pequenos","approach":"Preventive Planning","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Sugerir medicação contínua como "proteção"","approach":"Perpetual Medication","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"C","intervention":"Focar exclusivamente em técnicas de relaxamento para "proteção"","approach":"Incomplete Planning","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Não discutir recaída; assumir que está curada","approach":"Avoidance of Preparation","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 11, 'Reflexão sobre Transformação: De Prisioneira a Livre', 'termination', 'Sessão reflexiva. Maria reconhece jornada: começou severamente restrita (não conseguia deixar casa, marido tinha que fazer compras), agora dirige, sai, viaja. Agorafobia tinha a prendido por 2 anos. Agora tem sua vida de volta. Sente-se empoderada ao reconhecer que conseguiu enfrentar seus maiores medos via exposição graduada. Consolida que a liberdade custou coragem, mas foi conquistada por ela, não entregue por outros.', '[{"option_letter":"A","intervention":"Facilitar reflexão profunda sobre transformação, celebrar empoderamento via ação própria, integrar aprendizados sobre coragem","approach":"Transformational Closure","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Focar em "ainda há situações que causa ansiedade"","approach":"Deficit Focus","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir mais terapia para "garantir"","approach":"Perpetual Treatment","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar rapidamente sem reflexão","approach":"Rushed Termination","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440001', 12, 'Encerramento: Especialista em Sua Própria Liberdade', 'termination', 'Sessão final. Maria deixa terapia com ferramentas portáteis: hierarquia de exposição, manejo de sensações físicas, plano de recaída, rede de suporte (marido, amigas). Mensagem central: "Você é agora especialista em sua própria liberdade. Você aprendeu que ação corajosa, mesmo com ansiedade, devolve a vida. Essa verdade é sua para sempre." Porta aberta para reforços futuros se necessário, mas Maria sai com confiança de que consegue gerir sua agorafobia.', '[{"option_letter":"A","intervention":"Consolidar autonomia, revisar ferramentas portáteis, celebrar empoderamento, deixar porta aberta para reforço futuro","approach":"Autonomous Empowerment","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Prescrever medicação indefinida como "manutenção"","approach":"Medication Dependency","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"C","intervention":"Terapia indefinida para "garantir"","approach":"Treatment Perpetuation","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar com aviso de "pode voltar a piorar"","approach":"Disempowerment","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- ============================================
-- STEP 4: Insert 12 sessions for TAG (Pedro)
-- Journey ID: 550e8400-e29b-41d4-a716-446655440000
-- ============================================
-- Template: Journey-001 (TAG - Generalized Anxiety Disorder)

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 1, 'Entendendo TAG: Preocupação Crônica Além do Controle', 'initial', 'Pedro, 42 anos, relata preocupação constante com saúde, finanças, desempenho no trabalho. Dorme mal, músculos tensionados. Preocupa-se com preocupação em si ("Vou pirar com essas preocupações"). Crença central: "Se não me preocupo, algo ruim vai acontecer." TAG é caracterizado por preocupação excessiva que Pedro não consegue controlar. Sessão inicial: psicoeducação sobre TAG, normalizando que preocupação é humana, mas TAG a exagera. Estabelece aliança e esperança de que TCC+ACT podem ajudar.', '[{"option_letter":"A","intervention":"Psicoeducação colaborativa sobre TAG como transtorno de preocupação excessiva, não fraqueza; esperança via TCC+ACT","approach":"Validation + Hope","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":4,"symptom_reduction":0}},{"option_letter":"B","intervention":"Focar em "eliminar preocupação" via relaxamento","approach":"Unrealistic Goal","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Explorar "por que" se preocupa tanto","approach":"Unproductive Analysis","is_optimal":false,"impact":{"rapport":5,"insight":5,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Medicar imediatamente sem psicoterapia","approach":"Medication Only","is_optimal":false,"impact":{"rapport":3,"insight":1,"behavioral_change":1,"symptom_reduction":2}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 2, 'Mapeando Correntes de Preocupação: Identificando Padrões', 'middle', 'Pedro traz diário de preocupações. Identifica correntes: saúde ("dor no peito = infarto") → financeiro ("vou perder tudo") → trabalho ("vou ser demitido"). Padrão central: interpretação catastrófica de ambiguidade. Você e Pedro mapeiam cada corrente, notando como uma alimenta outra. Técnica: "preocupação como hipótese, não como fato." Sessão estabelece que preocupação é tentativa frustrada de resolver problemas incertos.', '[{"option_letter":"A","intervention":"Mapear correntes colaborativamente, distinguir problemas reais de "e se" hipotéticos; começar a questionar certeza de catástrofes","approach":"Cognitive Mapping","is_optimal":true,"impact":{"rapport":8,"insight":8,"behavioral_change":5,"symptom_reduction":0}},{"option_letter":"B","intervention":"Focar exclusivamente na corrente de saúde (fazer exames médicos)","approach":"Reassurance Seeking","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir que não há padrão, "preocupação é normal"","approach":"Normalization Without Action","is_optimal":false,"impact":{"rapport":6,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Aumentar ansiolítico para dormir melhor","approach":"Symptom Suppression","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 3, 'Desafiando Pensamentos: De Catástrofe a Realidade', 'middle', 'Pedro relata que conseguiu "não checar" seu coração por 3 dias após sentir palpitação. Inicialmente o pânico subiu, mas depois habituou. Sessão trabalha em reestruturação cognitiva: "Qual é a evidência de que dor no peito = infarto?" Pedro lista: "Nenhuma. Fiz ECG normal." Você introduz "teste de hipótese": em vez de preocupar, reunir dados. Para cada preocupação, há teste possível. Sessão treina identificar preocupação como hipótese testável, não verdade.', '[{"option_letter":"A","intervention":"Treinar teste de hipótese para preocupações: qual evidência apoiaria a catástrofe? Qual refuta? Desenhar espectro de probabilidade","approach":"Empirical Questioning","is_optimal":true,"impact":{"rapport":8,"insight":9,"behavioral_change":7,"symptom_reduction":1}},{"option_letter":"B","intervention":"Fazer exames médicos adicionais para "confirmar" ou "descartar"","approach":"Reassurance Perpetuation","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Focar exclusivamente em relaxamento muscular","approach":"Somatic Focus Without Cognition","is_optimal":false,"impact":{"rapport":6,"insight":4,"behavioral_change":3,"symptom_reduction":1}},{"option_letter":"D","intervention":"Sugerir aceitar a preocupação como parte de si","approach":"Premature Acceptance","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 4, 'Tolerância à Incerteza: Aprender a Viver com "Não Sei"', 'middle', 'Pedro compartilha avanço: deixou de chamar amigos pedindo tranquilidade sobre saúde. Ainda preocupa, mas menos. Crença emerge: "Se não me preocupo, algo ruim vai acontecer. Preocupação previne desastre." Você trabalha em aceitação de incerteza: "Em 42 anos, tudo que você se preocupou aconteceu?" Resposta: "Talvez 5%." "Então preocupação não previne 95% dos perigos. O que ela faz?" Resposta: "Rouba alegria." Sessão: tolerância à incerteza é habilidade aprendida. Praticar deixar sem resposta, conviver com "não sei se vai dar certo" sem preocupar antes do acontecimento.', '[{"option_letter":"A","intervention":"Explorar ilusão de que preocupação previne desastres; treinar tolerância ao "não sei" via exposição a incerteza planejada","approach":"Uncertainty Tolerance Training","is_optimal":true,"impact":{"rapport":8,"insight":9,"behavioral_change":7,"symptom_reduction":1}},{"option_letter":"B","intervention":"Fornecer garantias: "não vai acontecer nada ruim"","approach":"False Reassurance","is_optimal":false,"impact":{"rapport":5,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir seguro de tudo como proteção","approach":"Avoidance Via Safety Behaviors","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Aceitar preocupação cronicamente e adaptar vida","approach":"Accommodation","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 5, 'Mindfulness e Observação: Assistindo a Preocupação Sem Luta', 'middle', 'Pedro praticou deixar pensamentos negativos surgirem sem agir (não checar, não chamar médico, não procrastinar trabalho). Inicialmente difícil, agora habituado. Descreveu: "Surge a preocupação, vejo ela, ela passa." Sessão aprofunda mindfulness: observação sem julgamento, sem fusão. Quando pensa "vou perder meu emprego", pode notar "tenho o pensamento de perda de emprego, parece real porque estou preocupado, mas é hipótese, não fato." Prática: noticing vs. believing.', '[{"option_letter":"A","intervention":"Aprofundar mindfulness e cognitive defusion: ensinar observação de pensamentos sem ação; treinar espaço entre pensamento e crença","approach":"Mindfulness + Cognitive Defusion","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Focar em"eliminar" pensamentos negativos","approach":"Thought Suppression","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aumentar relaxamento para "controlar" preocupação","approach":"Somatic Control","is_optimal":false,"impact":{"rapport":6,"insight":4,"behavioral_change":3,"symptom_reduction":1}},{"option_letter":"D","intervention":"Voltar a fazer listas de "assuntos para resolver"","approach":"Rumination Perpetuation","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 6, 'Ação Alinhada com Valores: Vivendo Além da Preocupação', 'advanced', 'Pedro dorme melhor (6-7 horas). Preocupação ainda surge, mas não domina. Foco muda para ACT: o que é importante para Pedro além de estar "seguro"? Identifica: relacionamento (negligenciado por preocupação com trabalho), saúde (exercício, alimentação), crescimento profissional. Sessão planeja ações pequenas alinhadas com valores: janta com esposa esta semana (relacionamento), caminhada 3x/semana (saúde), aprender nova habilidade (crescimento). Preocupação pode continuar, mas ação prossegue.', '[{"option_letter":"A","intervention":"Mapear valores profundos, planejar ações concretas mesmo com preocupação presente; enfatizar que ação, não controle de ansiedade, cria vida significativa","approach":"Values-Driven Action","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":2}},{"option_letter":"B","intervention":"Focar em atingir "zero preocupação" antes de agir","approach":"Prerequisite for Action","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aumentar trabalho por medo de não conseguir o que quer","approach":"Work-Based Anxiety","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Simplificar vida para reduzir área de preocupação","approach":"Limitation Instead of Growth","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 7, 'Consolidação de Ganhos: Preocupação Controlada, Vida Ativa', 'advanced', 'Pedro conseguiu manter exercício regular, passou tempo com esposa, aprendeu bases de novo software no trabalho. Preocupação entre 3-4/10 (iniciou 8/10). Qualidade de vida retornou. Sessão valida transformação: não eliminou preocupação (seria expectativa irreal para TAG), mas mudou relação com ela e consegue viver alinhado com valores. Discussão sobre manutenção: continuar práticas (mindfulness, ação alinhada com valores, teste de hipótese) regularmente.', '[{"option_letter":"A","intervention":"Celebrar transformação real (não eliminação, mas funcionalidade restaurada); revisar ferramentas de manutenção; validar que vida significativa é alcançável com TAG","approach":"Realistic Celebration","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":2}},{"option_letter":"B","intervention":"Sugerir que se preocupação voltar é fracasso","approach":"Unrealistic Expectations","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aumentar medicação para "manutenção"","approach":"Medication Escalation","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"D","intervention":"Encerrar abruptamente sem discussão de recaída","approach":"Unpreparedness for Relapse","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 8, 'Manejo de Recaída Leve: Preocupação Aumentada no Contexto de Stress', 'advanced', 'Período de stress no trabalho (reestruturação) gerou aumento de preocupação (6/10). Pedro notou rapidamente o padrão. Sessão reativa ferramentas: não tentou suprimir preocupação, aceitou enquanto agia (trabalho importante, também tempo com família). Preocupação naturalmente reduziu conforme situação se resolveu. Sessão consolida que preocupação é esperada sob stress, mas não precisa interromper ação e vida.', '[{"option_letter":"A","intervention":"Normalizar aumento sob stress como esperado; validar que conseguiu agir apesar de preocupação; reativar ferramentas rapidamente","approach":"Stress Normalization","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Sugerir que falhou e precisa de internamento","approach":"Catastrophization","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}},{"option_letter":"C","intervention":"Aumentar medicação durante stress","approach":"Pharmaceutical Escalation","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"D","intervention":"Parar terapia e aceitar preocupação crônica","approach":"Learned Helplessness","is_optimal":false,"impact":{"rapport":3,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 9, 'Integrando Aprendizados: TAG não é Identidade, é Condição Tratável', 'advanced', 'Pedro compartilha insight: "Não sou mais 'o cara preocupado'. Sou uma pessoa que às vezes preocupa excessivamente, mas sabe lidar." Transformação de identidade é significativa. Sessão consolida que TAG é transtorno tratável, não traço de personalidade. Ferramentas adquiridas (teste de hipótese, tolerância a incerteza, ação alinhada com valores, mindfulness) são permanentes. Discussão sobre como pode usar essas habilidades em outros contextos de vida.', '[{"option_letter":"A","intervention":"Celebrar transformação de identidade; consolidar que TAG é condição, não essência; integrar ferramentas como permanentemente suas","approach":"Identity Transformation","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":2}},{"option_letter":"B","intervention":"Focar em "ainda pode piorar"","approach":"Threat Focus","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir terapia indefinida como manutenção","approach":"Treatment Perpetuation","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar e não discutir seguimento","approach":"Abrupt Termination","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 10, 'Plano de Prevenção de Recaída: Vigilância Inteligente', 'termination', 'Pedro e terapeuta criam plano de recaída. Gatilhos: stress profissional, isolamento social, parar exercício. Sinais de alerta: volta de insônia, checklists mentais, busca por reassegurança, isolamento. Ação imediata: retomar mindfulness, exercício, conversa com esposa sobre sentimentos, considerar booster terapêutico se não melhora em 1-2 semanas. Ênfase: recaída leve é normal com TAG, mas ação rápida previne piora.', '[{"option_letter":"A","intervention":"Criar plano detalhado de recaída com gatilhos, sinais, e ações; enfatizar ação rápida como chave; deixar porta aberta para booster","approach":"Relapse Prevention","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":8,"symptom_reduction":2}},{"option_letter":"B","intervention":"Prescrever medicação contínua como proteção","approach":"Perpetual Medication","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"C","intervention":"Não discutir recaída; assumir cura permanente","approach":"Overconfidence","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Sugerir terapia indefinida como seguro","approach":"Over-treatment","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 11, 'Reflexão Profunda: Vida Reclamada de TAG', 'termination', 'Sessão reflexiva. Pedro relembra: começou com preocupação incontrolável (8/10), insônia, isolamento. Agora dorme bem, conectado com esposa, crescendo no trabalho, exercitando, vivendo alinhado com valores. Reconhece que TAG não desapareceu, mas deixou de controlar vida. Insight: "A maior vitória não foi eliminar preocupação, foi deixar de ser escravizado por ela." Sente-se empoderado, orgulhoso de si mesmo pela coragem de enfrentar via terapia.', '[{"option_letter":"A","intervention":"Facilitar reflexão profunda sobre transformação de vida; celebrar empoderamento e autonomia conquistados; reconhecer coragem","approach":"Transformational Closure","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Focar em "ainda tem preocupação"","approach":"Deficit Focus","is_optimal":false,"impact":{"rapport":4,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"C","intervention":"Sugerir mais terapia para ficar "mais seguro"","approach":"Perpetual Treatment","is_optimal":false,"impact":{"rapport":5,"insight":4,"behavioral_change":2,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar abruptamente","approach":"Rushed Termination","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO journey_sessions (id, journey_id, session_number, session_title, session_phase, context, options, created_at, updated_at) VALUES
(gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 12, 'Encerramento: Especialista em Sua Própria Saúde Mental', 'termination', 'Sessão final. Pedro deixa com ferramentas portáteis: teste de hipótese, tolerância a incerteza, mindfulness, valores e ação alinhada, plano de recaída. Mensagem central: "Você agora é especialista em lidar com TAG. Você sabe que preocupação excessiva não é verdade, que tolerância a incerteza é habilidade aprendida, que ação alinhada com valores cria vida significativa apesar de ansiedade. Essas verdades são suas para sempre." Porta aberta para reforços futuros. Pedro sai com confiança de autonomia.', '[{"option_letter":"A","intervention":"Consolidar autonomia, revisar ferramentas portáteis, celebrar especialidade conquistada sobre si mesmo, deixar porta aberta para reforço","approach":"Autonomous Mastery","is_optimal":true,"impact":{"rapport":9,"insight":9,"behavioral_change":9,"symptom_reduction":3}},{"option_letter":"B","intervention":"Prescrever medicação indefinida","approach":"Medication Dependency","is_optimal":false,"impact":{"rapport":4,"insight":2,"behavioral_change":1,"symptom_reduction":1}},{"option_letter":"C","intervention":"Terapia indefinida como seguro","approach":"Treatment Perpetuation","is_optimal":false,"impact":{"rapport":5,"insight":3,"behavioral_change":1,"symptom_reduction":0}},{"option_letter":"D","intervention":"Encerrar com aviso de "pode voltar a piorar"","approach":"Disempowerment","is_optimal":false,"impact":{"rapport":2,"insight":1,"behavioral_change":0,"symptom_reduction":0}}]'::jsonb, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- ============================================
-- FINAL VALIDATION
-- ============================================

SELECT 'FINAL COUNT' as step,
  (SELECT COUNT(*) FROM journey_sessions WHERE journey_id = '550e8400-e29b-41d4-a716-446655440002') as depressao_sessions,
  (SELECT COUNT(*) FROM journey_sessions WHERE journey_id = '550e8400-e29b-41d4-a716-446655440001') as agorafobia_sessions,
  (SELECT COUNT(*) FROM journey_sessions WHERE journey_id = '550e8400-e29b-41d4-a716-446655440000') as tag_sessions,
  (SELECT COUNT(*) FROM journey_sessions WHERE journey_id IN ('550e8400-e29b-41d4-a716-446655440002','550e8400-e29b-41d4-a716-446655440001','550e8400-e29b-41d4-a716-446655440000')) as total_sessions;

COMMIT;

-- ============================================
-- SUCCESS MESSAGE
-- ============================================
-- ✅ If you reach here, all 36 inserts succeeded!
--
-- Backend Test: GET /api/journeys → should list 10 journeys (7 complete + 3 new with 12 sessions each)
-- Browser Test: localStorage check + navigate through all 12 sessions of each journey
-- Expected: No 404 errors
--
-- Query to verify:
-- SELECT COUNT(*), journey_id FROM journey_sessions
-- WHERE journey_id IN ('550e8400-e29b-41d4-a716-446655440002','550e8400-e29b-41d4-a716-446655440001','550e8400-e29b-41d4-a716-446655440000')
-- GROUP BY journey_id;
